Homework#8
yeargor/AndersenJava pull request #18
Opened 2024-09-27 19:48 UTC by yeargor

2024-09-28 05:45 UTC, Alexmansar requested changes
@yeargor HI)) in general good job)) just small comments))

2024-09-28 05:45 UTC, Alexmansar commented on src/main/java/Homework8/config/JDBCConfig.java
> +    public static Session getSession(){ return getSessionFactory().getCurrentSession(); }
fix formatting

2024-09-28 05:45 UTC, Alexmansar commented on src/main/java/Homework8/config/JDBCConfig.java
> +    public static final String HIBERNATE_CFG_XML = "hibernate.cfg.xml";
couldbe private

2024-09-28 05:45 UTC, Alexmansar commented on src/main/java/Homework8/model/Ticket.java
> +        this.creationDate = creationDate;
also, you can crete this one in the constructor

2024-09-28 05:45 UTC, Alexmansar commented on src/main/java/Homework8/model/User.java
> +        this.creationDate = creationDate;
same

2024-09-28 05:45 UTC, Alexmansar commented on src/main/java/Homework8/repository/TicketRepository.java
> +            return ticket;
could be just 
return session.get(Ticket.class, id);

2024-09-28 05:45 UTC, Alexmansar commented on src/main/java/Homework8/repository/UserRepository.java
> +            return user;
same

2024-09-29 09:33 UTC, yeargor commented on src/main/java/Homework8/model/Ticket.java
> +        this.creationDate = creationDate;
Could you please explain what I need to do? I dont understand a bit, sorry

2024-09-30 05:03 UTC, Alexmansar commented on src/main/java/Homework8/model/Ticket.java
> +        this.creationDate = creationDate;
this. this.creationDate  = new Date(System.currentTimeMillis()
and remove from the constructor parameters

2024-10-01 15:16 UTC, Alexmansar approved these changes
@yeargor Hi)) please, merge it)) good job

2024-10-01 15:26 UTC, merged