Features spring#3
yeargor/AndersenJava pull request #21
Opened 2024-10-11 16:45 UTC by yeargor

2024-10-11 18:11 UTC, Alexmansar requested changes
@yeargor Hi) I have small comments. Please check and fix it)

2024-10-11 18:11 UTC, Alexmansar commented on src/main/java/Homework11/controller/HelloController.java
> +        return ticketRepository.findById(5);
You need to create some service that will work with repo. In this service you need to prepare data for the controller. In your case - your service should return a Ticket. Not Optional. This conversion from Optional to Ticket is the responsibility of the service.

2024-10-11 18:11 UTC, Alexmansar commented on src/main/java/Homework11/model/User.java
> +@EntityListeners(AuditingEntityListener.class)
why we need it?

2024-10-11 18:35 UTC, yeargor commented on src/main/java/Homework11/model/User.java
> +@EntityListeners(AuditingEntityListener.class)
@Alexmansar, If we are talking about @EntityListeners(AuditingEntityListener.class), so it's needed to automatically generate date on "creationDate" field, which is also marked with @CreatedDate annotation. Those two annotations working together as much as I know

2024-10-11 18:36 UTC, yeargor commented on src/main/java/Homework11/controller/HelloController.java
> +        return ticketRepository.findById(5);
I will fix it in a few moments

2024-10-12 08:19 UTC, Alexmansar commented on src/main/java/Homework11/model/User.java
> +@EntityListeners(AuditingEntityListener.class)
ok) o problem)) its good that you invest the question)

2024-10-12 08:20 UTC, Alexmansar approved these changes
@yeargor Please, merge it)) good job

2024-10-17 07:29 UTC, merged